version: '3.8'

services:
  banger-link:
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banger-link
    restart: unless-stopped
    environment:
      - DATA_DIR=/app/data
      - DOWNLOAD_DIR=/app/data/downloads
      - IGNORED_DOMAINS=youtube.com;m.youtube.com;youtu.be
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
  
  banger_web:
    user: "node:node"
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/db_music.json
    build:
      context: ./banger_web
      dockerfile: Dockerfile
    container_name: banger-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - /usr/bin/flock:/usr/bin/flock
      - /bin/flock:/bin/flock
    depends_on:
      - banger-link
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
