version: "3"
services:
  banger-link:
    image: banger-link
    container_name: bot
    build: .
    environment:
      YOUTUBE_API_KEY: 
      TELEGRAM_API_KEY: 
      IGNORED_DOMAINS: "youtube.com;m.youtube.com;youtu.be"
      DOWNLOAD_DIR: '/app/downloads'
      DATA_DIR: '/app/data'
    volumes:
      - ./data:/app/data
