version: "3"
services:
  banger-link:
    build: .
    environment:
      YOUTUBE_API_KEY: 
      TELEGRAM_API_KEY: 
      IGNORED_DOMAINS: "youtube.com;m.youtube.com;youtu.be"
      DOWNLOAD_DIR: '/app/downloads'
